### ISSUE TITLE
[Indexer] Add full test suite and improve test coverage

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts-indexer#23]

**Comment by Jipperism** [comment]
@bitbeckers working on this now and I'm noticing that we fail using a `console.error(message); return;` in many places. Is there a reason we are using this pattern instead of throwing errors? I personally prefer throwing and catching errors as a control flow.

**Comment by Jipperism** [comment]
@bitbeckers also, should we consider using something like zod for checking wether an object is of the desire shape/type? To replace those kind of methods:

```
export const isAttestation = (data: unknown): data is Attestation => {
  return (
    typeof data === "object" &&
    data !== null &&
    "uid" in data &&
    "schema" in data &&
    "refUID" in data &&
    "time" in data &&
    "expirationTime" in data &&
    "revocationTime" in data &&
    "recipient" in data &&
    typeof data.recipient === "string" &&
    isAddress(data.recipient) &&
    "revocable" in data &&
    typeof data.revocable === "boolean" &&
    "attester" in data &&
    typeof data.attester === "string" &&
    isAddress(data.attester) &&
    "data" in data
  );
};
```

I guess performance would be worse, but readability would go up and there's a better chance of it being bug free?

**Comment by bitbeckers** [comment]
> @bitbeckers working on this now and I'm noticing that we fail using a `console.error(message); return;` in many places. Is there a reason we are using this pattern instead of throwing errors? I personally prefer throwing and catching errors as a control flow.

No only that we don't need to throw since Sentry can catch logs, but happy to catch everything at the top level. Feel free to create a ticket

**Comment by bitbeckers** [comment]
> @bitbeckers also, should we consider using something like zod for checking wether an object is of the desire shape/type? To replace those kind of methods:
> 
> ```
> export const isAttestation = (data: unknown): data is Attestation => {
>   return (
>     typeof data === "object" &&
>     data !== null &&
>     "uid" in data &&
>     "schema" in data &&
>     "refUID" in data &&
>     "time" in data &&
>     "expirationTime" in data &&
>     "revocationTime" in data &&
>     "recipient" in data &&
>     typeof data.recipient === "string" &&
>     isAddress(data.recipient) &&
>     "revocable" in data &&
>     typeof data.revocable === "boolean" &&
>     "attester" in data &&
>     typeof data.attester === "string" &&
>     isAddress(data.attester) &&
>     "data" in data
>   );
> };
> ```
> 
> I guess performance would be worse, but readability would go up and there's a better chance of it being bug free?

Sure, good idea. Feel free to create a ticket

**Comment by bitbeckers** [comment]
Thanks for adding the tests @Jipperism (and the zod schemas). For clarity: we agreed to merge everything into develop and will be adding tests for additional features and bugs.
