### ISSUE TITLE
[Indexer] A claimed token should indicate whether it was claimed from an allowlist

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts-indexer#26]
### Describe the feature you'd like to request

a way of flagging in the subgraph whether a hypercert token was claimed from an allowlist (or claimed by creating a degenerate hypercert with no allowlist)

### Describe the solution you'd like

a boolean field in `claimToken` that specifies whether it was claimed from an allowlist or not

### Describe alternatives you've considered

From Lucian at Gitcoin:

> I had a question regarding the update to the Hypercerts stamp, to restrict it to only hypercerts created with batchMintClaimsFromAllowlists. I was just wondering if you had an idea in mind for the source we should use for that data. If not, I might look into indexing the events on our side!. We were previously using the Graph for hypercerts but it doesn't look like that will tell me the method used for minting. 
> Oh wait! It's the allowlists in the subgraph, isn't it? I think I'm good to go!
> Oh nope that's not it, it'd be the handleBatchValueTransfer function in the subgraph code. And it doesn't look like that currently stores any indication on the ClaimToken of whether or not it was created with a batchMintClaimsFromAllowlists call
> It looks like the Hypercerts contract is only ever going to emit a BatchValueTransfer from the 0 address for a batchMintClaimsFromAllowlists call. Would it work for you if I made a PR for your repo to add a flag to the ClaimToken object that gets set in this scenario? 
> That'd probably be the easiest thing, especially if you all would appreciate that info on your end as well! I'm also happy to do the lookup and/or indexing on our side instead

**Comment by bitbeckers** [comment]
Technically this is currently in the new indexer, closing this for now
