### ISSUE TITLE
Indexer only picking up the first evaluation from each evaluator per hypercert

### ISSUE THREAD

**Issue by kristoferlund** [hypercerts-org/hypercerts-indexer#46]
## 1. Listing all evalutor evaluations

This are fetched from the hypercerts api. Two evaluations with the same referenced cert.

![Image](https://github.com/hypercerts-org/hypercerts-evaluator/assets/9698363/8937bc08-c0b4-4444-ac57-af1778aca6b0)

![Image](https://github.com/hypercerts-org/hypercerts-evaluator/assets/9698363/c5f1669c-2a49-4606-a39e-4bc9f526680b)

## 2. Hypercerts indexer returns only one row 

![Image](https://github.com/hypercerts-org/hypercerts-evaluator/assets/9698363/6c337efc-7928-4057-86ef-1eb285e72d2c)

**Comment by bitbeckers** [comment]
Fixed in https://github.com/hypercerts-org/hypercerts-indexer/pull/50
